name: "release"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: ["hany", "hany_web", "hany_ml", "hany_livebook"]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push (base)
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.release }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.release }}:${{ github.sha }}
          build-args: |
            _MIX_ENV=prod
            _RELEASE_NAME=${{ matrix.release }}
